---
driver:
  name: docker_cli

transport:
  name: docker_cli

platforms:
#  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.6
#  - name: fedora-20

suites:
  - name: chef
    provisioner:
      name: chef_zero
    driver:
      dns:
        - 8.8.8.8
        - 199.85.126.10

  - name: ansible
    provisioner:
      name: ansible_playbook
      playbook: test/integration/ansible/default.yml
      hosts: 127.0.0.1
    verifier:
      ruby_bindir: /usr/bin
