---
driver:
  name: docker_cli

transport:
  name: docker_cli
  lxc_driver: true

driver_config:
  hostname: example.local

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: default
    run_list:
      - recipe[integration-test::default]
    attributes:
