---
driver:
  name: docker_cli

transport:
  name: docker_cli
  lxc_driver: true

driver_config:
  hostname: example.local

platforms:
  - name: ubuntu-12.04
  - name: centos-6.4

suites:
  - name: chef
    provisioner:
      name: chef_zero
    run_list:
      - recipe[integration-test::default]
    attributes:

  - name: ansible
    provisioner:
      name: ansible_playbook
      playbook: test/integration/ansible/default.yml
      hosts: 127.0.0.1
